all:
	gcc command_tree.c shell.c buffered_string.c autocomplete.c history.c prompt.c colors.c string_utils.c executor.c token.c input_reader.c symbol_table.c init.c builtin_utilities/exit.c builtin_utilities/clera.c builtin_utilities.c builtin_utilities/ht.c builtin_utilities/dump.c builtin_utilities/builtins.c builtin_utilities/cd.c -o trshell.o

clean:
	rm *.o
